  
version: '3.4'
x-build: &build
  context: ../../../
  dockerfile: Dockerfile
  
x-shared: &common
  ipc: host
  build:
    context: ../../../
    dockerfile: Dockerfile
    args:
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DEV_SOURCE=${DEV_SOURCE}
  volumes:
    - ../../../:/src/minnie-nda
    - ${NOTEBOOK_PATH}:/notebooks
    - ${DATA_PATH}:/data
    - /mnt:/mnt
  env_file:
    - .env

services:
  notebook:
    <<: *common
    ports:
        - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    entrypoint: /src/minnie-nda/deploy/personal/zhuokun/notebook.sh
  bin:
    <<: *common
    entrypoint: /bin/bash