  
version: '3.4'
x-build: &build
  context: ../../
  dockerfile: Dockerfile
  
x-shared: &common
  ipc: host
  build:
    context: ../../
    dockerfile: Dockerfile
  volumes:
    - ../../:/src/microns-nda
    - /mnt:/mnt
    - ${NOTEBOOK_PATH}:/notebook
    - ${DATA_PATH}:/data
  env_file:
    - .env

services:
  notebook:
    <<: *common
    ports:
        - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    entrypoint: /src/microns-nda/deploy/notebook.sh
  bin:
    <<: *common
    entrypoint: /bin/bash